apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  selector:
    app: haproxy 
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32080  # Define the desired NodePort value here
  type: NodePort  # Set the service type to NodePort

